import type { WeekendSpot } from '@/types/weekendSpot'

export const weekendSpots: WeekendSpot[] = [
  {
    id: 'kpop-music-store',
    emoji: '💿',
    titleZh: 'KPOP MUSIC',
    titleEn: 'KPOP MUSIC',
    cityZh: '台北',
    cityEn: 'Taipei',
    categoryZh: 'K-POP 專輯/周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '依官方社群公告為準',
    whenEn: 'Follow official social updates',
    summaryZh: '主打韓流專輯與周邊資訊，購買前建議先看官方最新公告。',
    summaryEn: 'Focused on K-POP albums and goods; check official updates before visiting.',
    detailZh: '以韓流實體專輯與周邊代購資訊為主，開團與到貨時間通常在社群公告。',
    detailEn: 'Focuses on K-POP albums and merch updates, with release and shipping timing posted on social channels.',
    buyChannels: [
      {
        nameZh: '官方社群（新品/預購）',
        nameEn: 'Official Social (New Drops / Pre-order)',
        url: 'https://www.facebook.com/kpopmusic.tw/',
        noteZh: '通常會先公布可購買的周邊與預購規則。',
        noteEn: 'Usually announces available merch and pre-order rules first.',
      },
      {
        nameZh: 'Google 地圖門市資訊',
        nameEn: 'Google Maps Store Info',
        url: 'https://www.google.com/maps/search/KPOP+MUSIC+Taipei',
        noteZh: '查營業時間與現場評價，出發前可先確認。',
        noteEn: 'Check opening hours and recent reviews before visiting.',
      },
    ],
    sourceName: 'KPOP MUSIC 官方社群',
    sourceUrl: 'https://www.facebook.com/kpopmusic.tw/',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'five-music',
    emoji: '🏬',
    titleZh: '五大唱片',
    titleEn: 'Five Music',
    cityZh: '全台/線上',
    cityEn: 'Taiwan / Online',
    categoryZh: '唱片連鎖',
    categoryEn: 'Record Chain Store',
    whenZh: '門市與客服時間依官網公告',
    whenEn: 'Store and support hours on official site',
    summaryZh: '可查韓語專區、周邊商品與門市資訊，適合找 K-POP 與實體專輯。',
    summaryEn: 'Includes Korean category, goods section, and store info for album shopping.',
    detailZh: '提供全台門市資訊與線上購買入口，適合查現貨、預購與周邊分類。',
    detailEn: 'Provides branch details and online purchase entries for stock checks, pre-orders, and merch categories.',
    buyChannels: [
      {
        nameZh: '五大唱片門市查詢',
        nameEn: 'Five Music Branch Lookup',
        url: 'https://www.5music.com.tw/store.asp',
        noteZh: '可查看全台門市地址與營業資訊。',
        noteEn: 'View Taiwan branch addresses and business hours.',
      },
      {
        nameZh: '五大唱片線上商店',
        nameEn: 'Five Music Online Store',
        url: 'https://www.5music.com.tw/',
        noteZh: '線上下單可查看專輯與部分周邊。',
        noteEn: 'Order online for albums and selected merch.',
      },
    ],
    sourceName: '五大唱片官網',
    sourceUrl: 'https://www.5music.com.tw/store.asp',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'ccr-records',
    emoji: '🎵',
    titleZh: '佳佳唱片',
    titleEn: 'Chia Chyun Record (CCR)',
    cityZh: '台北/線上',
    cityEn: 'Taipei / Online',
    categoryZh: '唱片行',
    categoryEn: 'Record Store',
    whenZh: '門市資訊請見官網門市頁',
    whenEn: 'See official store page for branch details',
    summaryZh: '提供韓語專輯、新品與預購資訊，並有獨立門市資訊頁。',
    summaryEn: 'Offers Korean albums, new releases, and pre-orders with dedicated store info.',
    detailZh: '可在線上查詢新品/預購，並透過門市頁確認實體店位置與營業時間。',
    detailEn: 'Check new releases and pre-orders online, then confirm physical store locations and hours on the store page.',
    buyChannels: [
      {
        nameZh: '佳佳唱片門市資訊',
        nameEn: 'CCR Store Branches',
        url: 'https://www.ccr.com.tw/Store.php',
        noteZh: '列出門市資訊，適合找實體通路。',
        noteEn: 'Lists branch details for in-person purchases.',
      },
      {
        nameZh: '佳佳唱片首頁（線上）',
        nameEn: 'CCR Homepage (Online)',
        url: 'https://www.ccr.com.tw/',
        noteZh: '可查專輯與預購資訊。',
        noteEn: 'Browse albums and pre-order listings.',
      },
    ],
    sourceName: '佳佳唱片官網',
    sourceUrl: 'https://www.ccr.com.tw/Store.php',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'hanteo-family-tw',
    emoji: '🗺️',
    titleZh: 'HANTEO Family 認證通路查詢',
    titleEn: 'HANTEO Family Certified Stores',
    cityZh: '全台',
    cityEn: 'Nationwide',
    categoryZh: '認證購買管道',
    categoryEn: 'Verified Purchase Channel',
    whenZh: '依網站即時資料',
    whenEn: 'Live list on official site',
    summaryZh: '可查 HANTEO 認證販售通路，頁面可見 FIVE MUSIC(台灣) 等店家。',
    summaryEn: 'Browse HANTEO-certified sellers, including entries like FIVE MUSIC (Taiwan).',
    detailZh: '適合先確認哪些通路屬於認證銷售點，再回到該店家官網或門市購買。',
    detailEn: 'Useful for verifying certified sellers before buying from each store website or branch.',
    buyChannels: [
      {
        nameZh: 'HANTEO 認證通路查詢',
        nameEn: 'HANTEO Certified Store Search',
        url: 'https://www.hanteochart.com/family/search',
        noteZh: '先查認證通路名單，再點入店家購買。',
        noteEn: 'Check certified channels first, then proceed to each seller.',
      },
      {
        nameZh: 'FIVE MUSIC（範例通路）',
        nameEn: 'FIVE MUSIC (Example Seller)',
        url: 'https://www.5music.com.tw/store.asp',
        noteZh: '可作為查到認證後的實際購買入口。',
        noteEn: 'An example buy entry after confirming certification.',
      },
    ],
    sourceName: 'HANTEO Family Search',
    sourceUrl: 'https://www.hanteochart.com/family/search',
    verifiedAt: '2026-03-27',
  },
]
