import type { WeekendSpot } from '@/types/weekendSpot'

export const weekendSpots: WeekendSpot[] = [
  {
    id: 'kpop-music-store',
    emoji: '💿',
    titleZh: 'KPOP MUSIC',
    titleEn: 'KPOP MUSIC',
    cityZh: '台北',
    cityEn: 'Taipei',
    categoryZh: 'K-POP 專輯/周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '依官方社群公告為準',
    whenEn: 'Follow official social updates',
    summaryZh: '主打韓流專輯與周邊資訊，購買前建議先看官方最新公告。',
    summaryEn: 'Focused on K-POP albums and goods; check official updates before visiting.',
    detailZh: '以韓流實體專輯與周邊代購資訊為主，開團與到貨時間通常在社群公告。',
    detailEn: 'Focuses on K-POP albums and merch updates, with release and shipping timing posted on social channels.',
    buyChannels: [
      {
        nameZh: '官方社群（新品/預購）',
        nameEn: 'Official Social (New Drops / Pre-order)',
        url: 'https://www.facebook.com/kpopmusic.tw/',
        noteZh: '通常會先公布可購買的周邊與預購規則。',
        noteEn: 'Usually announces available merch and pre-order rules first.',
      },
      {
        nameZh: 'Google 地圖門市資訊',
        nameEn: 'Google Maps Store Info',
        url: 'https://www.google.com/maps/search/KPOP+MUSIC+Taipei',
        noteZh: '查營業時間與現場評價，出發前可先確認。',
        noteEn: 'Check opening hours and recent reviews before visiting.',
      },
    ],
    sourceName: 'KPOP MUSIC 官方社群',
    sourceUrl: 'https://www.facebook.com/kpopmusic.tw/',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'five-music',
    emoji: '🏬',
    titleZh: '五大唱片',
    titleEn: 'Five Music',
    cityZh: '全台/線上',
    cityEn: 'Taiwan / Online',
    categoryZh: '唱片連鎖',
    categoryEn: 'Record Chain Store',
    whenZh: '門市與客服時間依官網公告',
    whenEn: 'Store and support hours on official site',
    summaryZh: '可查韓語專區、周邊商品與門市資訊，適合找 K-POP 與實體專輯。',
    summaryEn: 'Includes Korean category, goods section, and store info for album shopping.',
    detailZh: '提供全台門市資訊與線上購買入口，適合查現貨、預購與周邊分類。',
    detailEn: 'Provides branch details and online purchase entries for stock checks, pre-orders, and merch categories.',
    buyChannels: [
      {
        nameZh: '五大唱片門市查詢',
        nameEn: 'Five Music Branch Lookup',
        url: 'https://www.5music.com.tw/store.asp',
        noteZh: '可查看全台門市地址與營業資訊。',
        noteEn: 'View Taiwan branch addresses and business hours.',
      },
      {
        nameZh: '五大唱片線上商店',
        nameEn: 'Five Music Online Store',
        url: 'https://www.5music.com.tw/',
        noteZh: '線上下單可查看專輯與部分周邊。',
        noteEn: 'Order online for albums and selected merch.',
      },
    ],
    sourceName: '五大唱片官網',
    sourceUrl: 'https://www.5music.com.tw/store.asp',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'ccr-records',
    emoji: '🎵',
    titleZh: '佳佳唱片',
    titleEn: 'Chia Chyun Record (CCR)',
    cityZh: '台北/線上',
    cityEn: 'Taipei / Online',
    categoryZh: '唱片行',
    categoryEn: 'Record Store',
    whenZh: '門市資訊請見官網門市頁',
    whenEn: 'See official store page for branch details',
    summaryZh: '提供韓語專輯、新品與預購資訊，並有獨立門市資訊頁。',
    summaryEn: 'Offers Korean albums, new releases, and pre-orders with dedicated store info.',
    detailZh: '可在線上查詢新品/預購，並透過門市頁確認實體店位置與營業時間。',
    detailEn: 'Check new releases and pre-orders online, then confirm physical store locations and hours on the store page.',
    buyChannels: [
      {
        nameZh: '佳佳唱片門市資訊',
        nameEn: 'CCR Store Branches',
        url: 'https://www.ccr.com.tw/Store.php',
        noteZh: '列出門市資訊，適合找實體通路。',
        noteEn: 'Lists branch details for in-person purchases.',
      },
      {
        nameZh: '佳佳唱片首頁（線上）',
        nameEn: 'CCR Homepage (Online)',
        url: 'https://www.ccr.com.tw/',
        noteZh: '可查專輯與預購資訊。',
        noteEn: 'Browse albums and pre-order listings.',
      },
    ],
    sourceName: '佳佳唱片官網',
    sourceUrl: 'https://www.ccr.com.tw/Store.php',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'hanteo-family-tw',
    emoji: '🗺️',
    titleZh: 'HANTEO Family 認證通路查詢',
    titleEn: 'HANTEO Family Certified Stores',
    cityZh: '全台',
    cityEn: 'Nationwide',
    categoryZh: '認證購買管道',
    categoryEn: 'Verified Purchase Channel',
    whenZh: '依網站即時資料',
    whenEn: 'Live list on official site',
    summaryZh: '可查 HANTEO 認證販售通路，頁面可見 FIVE MUSIC(台灣) 等店家。',
    summaryEn: 'Browse HANTEO-certified sellers, including entries like FIVE MUSIC (Taiwan).',
    detailZh: '適合先確認哪些通路屬於認證銷售點，再回到該店家官網或門市購買。',
    detailEn: 'Useful for verifying certified sellers before buying from each store website or branch.',
    buyChannels: [
      {
        nameZh: 'HANTEO 認證通路查詢',
        nameEn: 'HANTEO Certified Store Search',
        url: 'https://www.hanteochart.com/family/search',
        noteZh: '先查認證通路名單，再點入店家購買。',
        noteEn: 'Check certified channels first, then proceed to each seller.',
      },
      {
        nameZh: 'FIVE MUSIC（範例通路）',
        nameEn: 'FIVE MUSIC (Example Seller)',
        url: 'https://www.5music.com.tw/store.asp',
        noteZh: '可作為查到認證後的實際購買入口。',
        noteEn: 'An example buy entry after confirming certification.',
      },
    ],
    sourceName: 'HANTEO Family Search',
    sourceUrl: 'https://www.hanteochart.com/family/search',
    verifiedAt: '2026-03-27',
  },
  {
    id: 'k-monstar',
    emoji: '⭐',
    titleZh: 'K-MONSTAR',
    titleEn: 'K-MONSTAR',
    cityZh: '台北／高雄',
    cityEn: 'Taipei / Kaohsiung',
    categoryZh: 'K-POP 專輯／周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '各門市營業時間依官網公告',
    whenEn: 'Hours vary by branch; check official site',
    summaryZh: '韓流專輯與周邊一站式選購，台北有三間門市、高雄夢時代也已開幕。',
    summaryEn: 'One-stop K-POP album and merch shopping; three Taipei branches plus Kaohsiung Dream Mall.',
    detailZh: '台北設有中山（赤峰街）、微風廣場、微風南山三間門市；2025年8月高雄夢時代（統一時代百貨B1）新店開幕，商品涵蓋專輯、手燈、小卡等官方周邊。',
    detailEn: 'Three Taipei locations (Zhongshan/Chifeng, Breeze Center, Breeze Nanshan) plus Kaohsiung Dream Mall (UNITED B1, opened Aug 2025). Stocks albums, light sticks, photo cards, and official goods.',
    buyChannels: [
      {
        nameZh: 'K-MONSTAR 官網',
        nameEn: 'K-MONSTAR Official Site',
        url: 'https://www.kmonstar.com.tw/',
        noteZh: '可查新品、預購與門市資訊。',
        noteEn: 'Browse new arrivals, pre-orders, and store locations.',
      },
      {
        nameZh: 'Instagram 官方帳號',
        nameEn: 'Official Instagram',
        url: 'https://www.instagram.com/kmonstar.kr/',
        noteZh: '最新到貨與活動第一手消息。',
        noteEn: 'Latest stock updates and event announcements.',
      },
    ],
    sourceName: 'K-MONSTAR 官網',
    sourceUrl: 'https://www.kmonstar.com.tw/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'willmusic',
    emoji: '🎧',
    titleZh: '微樂客 WillMusic',
    titleEn: 'WillMusic',
    cityZh: '台北／台中／高雄／桃園／基隆',
    cityEn: 'Taipei / Taichung / Kaohsiung / Taoyuan / Keelung',
    categoryZh: '日韓西洋專輯／周邊',
    categoryEn: 'J/K/Western Albums & Goods',
    whenZh: '各門市營業時間依官網公告',
    whenEn: 'Hours vary by branch; check official site',
    summaryZh: '販售日韓與西洋流行音樂專輯及演唱會周邊，全台多間門市且接受文化幣。',
    summaryEn: 'Stocks J-pop, K-pop, and Western albums plus concert merchandise; multiple branches nationwide accepting culture vouchers.',
    detailZh: '台北設有西門町、赤峰、ATT 4 FUN 信義三間門市，另有台中綠園道、基隆廟口、高雄新堀江、桃園統領等據點，支援現金、信用卡、文化幣與 LINE Pay。',
    detailEn: 'Taipei branches at Ximending, Chifeng, and ATT 4 FUN Xinyi; additional stores at Taichung Green Corridor, Keelung Miaokou, Kaohsiung Xinjuejing, and Taoyuan Uni-President. Accepts cash, credit card, culture vouchers, and LINE Pay.',
    buyChannels: [
      {
        nameZh: '門市資訊頁',
        nameEn: 'Store Locator',
        url: 'https://www.willmusic.com.tw/v2/Shop/StoreList/39836?lang=zh-TW',
        noteZh: '查各門市地址與營業時間。',
        noteEn: 'Find branch addresses and opening hours.',
      },
      {
        nameZh: '微樂客官網',
        nameEn: 'WillMusic Official Site',
        url: 'https://www.willmusic.com.tw/',
        noteZh: '線上瀏覽專輯與周邊商品。',
        noteEn: 'Browse albums and merchandise online.',
      },
    ],
    sourceName: '微樂客官網',
    sourceUrl: 'https://www.willmusic.com.tw/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'fairytree',
    emoji: '🧚',
    titleZh: '仙女樹 Fairytree',
    titleEn: 'Fairytree',
    cityZh: '台北／高雄／台南',
    cityEn: 'Taipei / Kaohsiung / Tainan',
    categoryZh: 'K-POP 專輯／拍貼機',
    categoryEn: 'K-POP Albums & Photo Booth',
    whenZh: '各門市營業時間依官方社群公告',
    whenEn: 'Check official social media for store hours',
    summaryZh: '台灣首家結合 K-POP 專輯與韓式拍貼機的複合店，已展店至台北、高雄、台南。',
    summaryEn: 'Taiwan\'s first store combining K-POP albums with Korean-style photo booths; branches in Taipei, Kaohsiung, and Tainan.',
    detailZh: '台北敦南門市位於大安區敦化南路一段177巷25號；高雄巨蛋門市位於鼓山區裕誠路1057號；台南亦設有 FOCUS 門市。專輯、手燈與偶像周邊齊全，並設置韓式大頭貼機供粉絲體驗。',
    detailEn: 'Taipei Dunnan branch at No. 25, Lane 177, Dunhua S. Rd. Sec. 1; Kaohsiung Dome branch at No. 1057, Yucheng Rd.; Tainan FOCUS branch also open. Stocks albums, light sticks, and idol goods alongside Korean-style photo booths.',
    buyChannels: [
      {
        nameZh: '仙女樹官網',
        nameEn: 'Fairytree Official Site',
        url: 'https://www.fairytree.com.tw/',
        noteZh: '查詢門市地址與最新商品。',
        noteEn: 'Find store locations and latest products.',
      },
      {
        nameZh: 'Instagram 官方帳號',
        nameEn: 'Official Instagram',
        url: 'https://www.instagram.com/fairytreee/',
        noteZh: '到貨與活動消息即時更新。',
        noteEn: 'Real-time updates on new stock and events.',
      },
    ],
    sourceName: '仙女樹官方社群',
    sourceUrl: 'https://www.fairytree.com.tw/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'fanme-taipei',
    emoji: '🌟',
    titleZh: 'FANME 台北小巨蛋店',
    titleEn: 'FANME Taipei Arena',
    cityZh: '台北',
    cityEn: 'Taipei',
    categoryZh: 'K-POP 官方授權周邊',
    categoryEn: 'K-POP Official Licensed Goods',
    whenZh: '週一至週日 11:00–21:00',
    whenEn: 'Mon–Sun 11:00–21:00',
    summaryZh: '全台首間 FANME 實體店，位於台北小巨蛋旁，百款韓星官方周邊與拆專桌一次滿足。',
    summaryEn: 'Taiwan\'s first FANME store, next to Taipei Arena; over 100 K-pop official goods and a merch-unboxing table.',
    detailZh: '2025年7月開幕，位於台北小巨蛋1-4號店鋪（松山區南京東路四段）。空間以銀灰主調搭配偶像親簽海報展示牆，販售 ATEEZ、NCT、KISS OF LIFE 等多團官方商品，設有拆專桌與會員 LUCKY DRAW 抽卡活動。',
    detailEn: 'Opened July 2025 at Taipei Arena Shop 1-4 (Nanjing E. Rd. Sec. 4, Songshan). Features idol-signed poster walls, official goods from ATEEZ, NCT, KISS OF LIFE, and more, plus an unboxing table and member LUCKY DRAW.',
    buyChannels: [
      {
        nameZh: 'FANME 官網',
        nameEn: 'FANME Official Site',
        url: 'https://www.fanmeofficial.com/',
        noteZh: '查詢商品與活動資訊。',
        noteEn: 'Browse products and event details.',
      },
      {
        nameZh: '台北小巨蛋官網',
        nameEn: 'Taipei Arena Official Site',
        url: 'https://www.arena.taipei/',
        noteZh: '確認演唱會場次與周邊店位置。',
        noteEn: 'Check concert schedules and store location within the venue.',
      },
    ],
    sourceName: 'FANME 官網',
    sourceUrl: 'https://www.fanmeofficial.com/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'all-my-day',
    emoji: '🎀',
    titleZh: 'ALL MY DAY',
    titleEn: 'ALL MY DAY',
    cityZh: '台北',
    cityEn: 'Taipei',
    categoryZh: 'K-POP 專輯／周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '平日 11:00–20:00 假日 11:00–21:00',
    whenEn: 'Weekdays 11:00–20:00 / Holidays 11:00–21:00',
    summaryZh: '2017 年創立，2024 年在信義區開設第一間實體店，手燈、偶像周邊與專輯品項豐富。',
    summaryEn: 'Founded 2017; first physical store opened in Xinyi in 2024 with a wide selection of light sticks, idol goods, and albums.',
    detailZh: '信義門市地址：台北市信義區莊敬路423巷8弄10號（捷運象山站2號出口）；赤峰門市：台北市大同區赤峰街23巷15號（捷運中山站）。接受現金、信用卡與文化幣。',
    detailEn: 'Xinyi branch: No. 10, Alley 8, Lane 423, Zhuangjing Rd., Xinyi Dist. (MRT Xiangshan Exit 2). Chifeng branch: No. 15, Lane 23, Chifeng St., Datong Dist. (MRT Zhongshan). Accepts cash, credit card, and culture vouchers.',
    buyChannels: [
      {
        nameZh: 'ALL MY DAY Facebook',
        nameEn: 'ALL MY DAY Facebook',
        url: 'https://www.facebook.com/allmyday.tw/',
        noteZh: '最新到貨、活動與門市公告。',
        noteEn: 'Latest arrivals, events, and store announcements.',
      },
      {
        nameZh: 'ALL MY DAY Threads',
        nameEn: 'ALL MY DAY Threads',
        url: 'https://www.threads.com/@allmyday.tw',
        noteZh: '即時更新商品與開箱資訊。',
        noteEn: 'Real-time product updates and unboxing posts.',
      },
    ],
    sourceName: 'ALL MY DAY Facebook',
    sourceUrl: 'https://www.facebook.com/allmyday.tw/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'boss-daren-kaohsiung',
    emoji: '👑',
    titleZh: '社長大人',
    titleEn: 'Boss Daren',
    cityZh: '高雄／台北／台中／台南',
    cityEn: 'Kaohsiung / Taipei / Taichung / Tainan',
    categoryZh: 'K-POP 專輯／周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '各門市營業時間依官方社群公告',
    whenEn: 'Check official social media for store hours',
    summaryZh: '高雄新崛江老字號 K-POP 專輯店，以進貨速度快、手燈周邊貨源齊全著稱，全台多間分店。',
    summaryEn: 'Long-established K-POP store in Kaohsiung\'s Xinjuejing area, known for fast restocking and hard-to-find light sticks; branches across Taiwan.',
    detailZh: '旗艦店位於高雄市新興區五福二路127號（新崛江商圈）；另設台北站前、台中三民、台南北門等分店。以韓團限量手燈與周邊快速調貨見長，也有蝦皮線上通路。',
    detailEn: 'Flagship at No. 127, Wufu 2nd Rd., Xinxing Dist., Kaohsiung (Xinjuejing area); additional branches in Taipei Qianzhong, Taichung Sanmin, and Tainan Beimen. Known for fast procurement of limited light sticks; also sells on Shopee.',
    buyChannels: [
      {
        nameZh: '社長大人蝦皮賣場',
        nameEn: 'Boss Daren Shopee',
        url: 'https://shopee.tw/eason007361',
        noteZh: '線上查詢商品現貨與預購。',
        noteEn: 'Check in-stock items and pre-orders online.',
      },
      {
        nameZh: 'Google 地圖（高雄旗艦店）',
        nameEn: 'Google Maps (Kaohsiung Flagship)',
        url: 'https://www.google.com/maps/search/%E7%A4%BE%E9%95%B7%E5%A4%A7%E4%BA%BA+%E9%AB%98%E9%9B%84+%E4%BA%94%E7%A6%8F%E4%BA%8C%E8%B7%AF',
        noteZh: '查詢門市位置與評論。',
        noteEn: 'View store location and customer reviews.',
      },
    ],
    sourceName: 'Threads 高雄 KPOP 店整理',
    sourceUrl: 'https://www.threads.com/@card_mysterio/post/DCSAyXyzA3b',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'guangnan-xinjuejing',
    emoji: '🏪',
    titleZh: '光南大批發（新崛江店）',
    titleEn: 'Guangnan Wholesale (Xinjuejing)',
    cityZh: '高雄',
    cityEn: 'Kaohsiung',
    categoryZh: 'K-POP 專輯／文創',
    categoryEn: 'K-POP Albums & Stationery',
    whenZh: '依門市公告為準',
    whenEn: 'Follow store announcements',
    summaryZh: '高雄新崛江商圈內的光南門市二樓設有 K-POP 專區，適合一次採購專輯與文具周邊。',
    summaryEn: 'The Guangnan Wholesale store in Kaohsiung\'s Xinjuejing has a K-POP section on the 2nd floor for albums and stationery.',
    detailZh: '位於高雄市新興區文橫一路，二樓設有 K-POP 專輯陳列區，商品涵蓋專輯、文具、偶像周邊等，鄰近多家 K-POP 特色小店，適合一同逛街。',
    detailEn: 'Located on Wengheng 1st Rd., Xinxing Dist., Kaohsiung. The 2nd floor carries K-POP albums, stationery, and idol goods; surrounded by other specialty K-pop stores in the Xinjuejing area.',
    buyChannels: [
      {
        nameZh: '光南大批發官網',
        nameEn: 'Guangnan Official Site',
        url: 'https://www.guangnan.com.tw/',
        noteZh: '查詢全台門市與線上商品。',
        noteEn: 'Find branch info and browse online products.',
      },
      {
        nameZh: 'Google 地圖',
        nameEn: 'Google Maps',
        url: 'https://www.google.com/maps/search/%E5%85%89%E5%8D%97%E5%A4%A7%E6%89%B9%E7%99%BC+%E9%AB%98%E9%9B%84+%E6%96%B0%E5%B4%9B%E6%B1%9F',
        noteZh: '確認位置與門市評價。',
        noteEn: 'Check location and customer reviews.',
      },
    ],
    sourceName: 'Threads 高雄 KPOP 店整理',
    sourceUrl: 'https://www.threads.com/@card_mysterio/post/DCSAyXyzA3b',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'kpop-master-kaohsiung',
    emoji: '🃏',
    titleZh: 'KPOP研究所 K-POP Master',
    titleEn: 'K-POP Master',
    cityZh: '高雄',
    cityEn: 'Kaohsiung',
    categoryZh: 'K-POP 小卡專賣',
    categoryEn: 'K-POP Photo Card Specialty Store',
    whenZh: '依官方社群公告為準',
    whenEn: 'Follow official social updates',
    summaryZh: '高雄新崛江小卡專賣店，主打各式韓團小卡交易與販售，追星迷交流聖地。',
    summaryEn: 'Photo card specialty store in Kaohsiung\'s Xinjuejing; a hub for buying, selling, and trading K-pop photo cards.',
    detailZh: '位於高雄市新興區文橫一路5巷10號，專注於 K-POP 各團小卡的蒐集與交流，適合需要特定小卡的粉絲前往挖寶。',
    detailEn: 'Located at No. 10, Lane 5, Wengheng 1st Rd., Xinxing Dist., Kaohsiung. Specializes in K-POP photo card collecting and trading — ideal for fans hunting specific cards.',
    buyChannels: [
      {
        nameZh: 'Google 地圖',
        nameEn: 'Google Maps',
        url: 'https://www.google.com/maps/search/K-POP+Master+%E9%AB%98%E9%9B%84+%E6%96%B0%E5%B4%9B%E6%B1%9F',
        noteZh: '確認門市位置與最新評論。',
        noteEn: 'Check store location and recent reviews.',
      },
    ],
    sourceName: 'Threads 高雄 KPOP 店整理',
    sourceUrl: 'https://www.threads.com/@card_mysterio/post/DCSAyXyzA3b',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'tianlai-records',
    emoji: '🎼',
    titleZh: '天天來',
    titleEn: 'Tianlai Records',
    cityZh: '高雄',
    cityEn: 'Kaohsiung',
    categoryZh: 'K-POP 專輯／周邊',
    categoryEn: 'K-POP Albums & Goods',
    whenZh: '依官方社群公告為準',
    whenEn: 'Follow official social updates',
    summaryZh: '高雄新崛江老字號 K-POP 專輯店，與社長大人並列高雄最具代表性的追星通路。',
    summaryEn: 'A veteran K-POP album store in Kaohsiung\'s Xinjuejing, alongside Boss Daren as one of the most iconic fan shopping destinations in the city.',
    detailZh: '位於高雄市新興區文橫一路25巷32號，深耕高雄 K-POP 專輯市場多年，以實體現貨與快速補貨著稱。',
    detailEn: 'Located at No. 32, Lane 25, Wengheng 1st Rd., Xinxing Dist., Kaohsiung. A long-standing presence in Kaohsiung\'s K-pop market, known for in-stock availability and quick restocking.',
    buyChannels: [
      {
        nameZh: 'Google 地圖',
        nameEn: 'Google Maps',
        url: 'https://www.google.com/maps/search/%E5%A4%A9%E5%A4%A9%E4%BE%86+%E9%AB%98%E9%9B%84+%E6%96%B0%E5%B4%9B%E6%B1%9F',
        noteZh: '查詢門市位置與評論。',
        noteEn: 'Find store location and customer reviews.',
      },
    ],
    sourceName: 'Threads 高雄 KPOP 店整理',
    sourceUrl: 'https://www.threads.com/@card_mysterio/post/DCSAyXyzA3b',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'warner-music-tw',
    emoji: '🎤',
    titleZh: '華納音樂台灣官方商城',
    titleEn: 'Warner Music Taiwan Official Store',
    cityZh: '線上',
    cityEn: 'Online',
    categoryZh: '官方明星周邊',
    categoryEn: 'Official Artist Merchandise',
    whenZh: '24 小時線上購買',
    whenEn: '24/7 online',
    summaryZh: '華納音樂台灣官方商城，提供旗下藝人明星周邊正版商品，適合購買官方演唱會紀念品。',
    summaryEn: 'Official Warner Music Taiwan store with licensed artist merchandise and concert memorabilia.',
    detailZh: '華納音樂旗下藝人（含五月天、周杰倫部分商品）官方授權周邊集中販售，商品包含演唱會限定版、服裝、配件等，保證正版。',
    detailEn: 'Official licensed goods from Warner Music artists (including some Mayday and Jay Chou items), featuring concert exclusives, apparel, and accessories — all authentic.',
    buyChannels: [
      {
        nameZh: '華納音樂台灣官方商城',
        nameEn: 'Warner Music Taiwan Store',
        url: 'https://www.warnermusic.com.tw/categories/5dc26966156fce00235dd43c',
        noteZh: '直接線上瀏覽明星周邊商品。',
        noteEn: 'Browse official artist merchandise directly online.',
      },
    ],
    sourceName: '華納音樂台灣官方網站',
    sourceUrl: 'https://www.warnermusic.com.tw/',
    verifiedAt: '2026-04-09',
  },
  {
    id: 'keepstyles',
    emoji: '🛍️',
    titleZh: 'Keepstyles 官方演唱會周邊',
    titleEn: 'Keepstyles Official Merchandise',
    cityZh: '線上',
    cityEn: 'Online',
    categoryZh: '演唱會官方周邊',
    categoryEn: 'Official Concert Merchandise',
    whenZh: '24 小時線上購買',
    whenEn: '24/7 online',
    summaryZh: '專門販售演唱會官方授權周邊的線上平台，適合演唱會前後購買正版紀念品。',
    summaryEn: 'Online platform specializing in official licensed concert merchandise, ideal for buying authentic souvenirs before or after shows.',
    detailZh: '提供各大演唱會官方授權商品，涵蓋 T-shirt、手燈、托特包等，可在演唱會前先行網購，避免現場排隊。',
    detailEn: 'Offers officially licensed goods from major concerts including T-shirts, light sticks, and tote bags. Pre-ordering online helps skip queues at the venue.',
    buyChannels: [
      {
        nameZh: 'Keepstyles 官方周邊頁',
        nameEn: 'Keepstyles Official Merch Page',
        url: 'https://www.keepstyles.com/categories/official-merchandise',
        noteZh: '直接瀏覽各演唱會官方周邊。',
        noteEn: 'Browse official merchandise for various concerts.',
      },
    ],
    sourceName: 'Keepstyles 官網',
    sourceUrl: 'https://www.keepstyles.com/',
    verifiedAt: '2026-04-09',
  },
]
