#!/usr/bin/env python3
"""Generate SQL for artist watchlist from lib/artistInbox.ts."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INBOX_FILE = ROOT / "lib" / "artistInbox.ts"
OUT_FILE = ROOT / "supabase-artist-watchlist.sql"

HANDLE_RE = re.compile(r"@[\w._]+", re.UNICODE)


def parse_handles(text: str) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for match in HANDLE_RE.findall(text):
        handle = match.strip().lower()
        if handle not in seen:
            seen.add(handle)
            ordered.append(handle)
    return ordered


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_sql(handles: list[str]) -> str:
    values = ",\n".join(
        f"  ('{sql_escape(h)}', '{sql_escape(h.lstrip('@').replace('_', ' ').replace('.', ' '))}', 'unknown')"
        for h in handles
    )

    return f"""-- Artist watchlist bootstrap SQL\n-- Generated from lib/artistInbox.ts\n\ncreate table if not exists artist_watchlist (\n  id bigint generated by default as identity primary key,\n  instagram text not null unique,\n  name text not null,\n  region text not null default 'unknown',\n  source text not null default 'ig-inbox',\n  is_active boolean not null default true,\n  created_at timestamptz not null default now(),\n  updated_at timestamptz not null default now()\n);\n\ncreate index if not exists artist_watchlist_region_idx on artist_watchlist (region);\ncreate index if not exists artist_watchlist_active_idx on artist_watchlist (is_active);\n\ninsert into artist_watchlist (instagram, name, region)\nvalues\n{values}\non conflict (instagram) do update\nset\n  name = excluded.name,\n  updated_at = now();\n"""


def main() -> None:
    content = INBOX_FILE.read_text(encoding="utf-8")
    handles = parse_handles(content)
    sql = build_sql(handles)
    OUT_FILE.write_text(sql, encoding="utf-8")
    print(f"Generated {OUT_FILE} with {len(handles)} handles")


if __name__ == "__main__":
    main()
